from django.urls import path
from . import views

urlpatterns = [
    path(
        "accepted-currencies/",
        views.AcceptedCurrenciesListCreateView.as_view(),
        name="accepted-currencies-list-create",
    ),
    path(
        "accepted-currencies/<int:pk>/",
        views.AcceptedCurrenciesRetrieveUpdateDestroyView.as_view(),
        name="accepted-currencies-retrieve-update-destroy",
    ),
    path(
        "contract-terms/",
        views.ContractTermListCreateView.as_view(),
        name="contract-terms-list-create",
    ),
    path(
        "contract-terms/<int:pk>/",
        views.ContractTermRetrieveUpdateDestroyView.as_view(),
        name="contract-terms-retrieve-update-destroy",
    ),
    path(
        "employment-eligibilities/",
        views.EmploymentEligibilityListCreateView.as_view(),
        name="employment-eligibilities-list-create",
    ),
    path(
        "employment-eligibilities/<int:pk>/",
        views.EmploymentEligibilityRetrieveUpdateDestroyView.as_view(),
        name="employment-eligibilities-retrieve-update-destroy",
    ),
    path(
        "eor-prices/",
        views.EorPricesListCreateView.as_view(),
        name="eor-prices-list-create",
    ),
    path(
        "eor-prices/<int:pk>/",
        views.EorPricesRetrieveUpdateDestroyView.as_view(),
        name="eor-prices-retrieve-update-destroy",
    ),
    path(
        "health-insurances/",
        views.HealthInsuranceListCreateView.as_view(),
        name="health-insurances-list-create",
    ),
    path(
        "health-insurances/<int:pk>/",
        views.HealthInsuranceRetrieveUpdateDestroyView.as_view(),
        name="health-insurances-retrieve-update-destroy",
    ),
    path(
        "invoice-types/",
        views.InvoiceTypeListCreateView.as_view(),
        name="invoice-types-list-create",
    ),
    path(
        "invoice-types/<int:pk>/",
        views.InvoiceTypeRetrieveUpdateDestroyView.as_view(),
        name="invoice-types-retrieve-update-destroy",
    ),
    path(
        "marital-statuses/",
        views.MaritalStatusListCreateView.as_view(),
        name="marital-statuses-list-create",
    ),
    path(
        "marital-statuses/<int:pk>/",
        views.MaritalStatusRetrieveUpdateDestroyView.as_view(),
        name="marital-statuses-retrieve-update-destroy",
    ),
    path(
        "payroll-prices/",
        views.PayrollPricesListCreateView.as_view(),
        name="payroll-prices-list-create",
    ),
    path(
        "payroll-prices/<int:pk>/",
        views.PayrollPricesRetrieveUpdateDestroyView.as_view(),
        name="payroll-prices-retrieve-update-destroy",
    ),
    path(
        "products/", views.ProductListCreateView.as_view(), name="products-list-create"
    ),
    path(
        "products/<int:pk>/",
        views.ProductRetrieveUpdateDestroyView.as_view(),
        name="products-retrieve-update-destroy",
    ),
    path(
        "payroll-statuses/",
        views.PayrollStatusListCreateView.as_view(),
        name="payroll-statuses-list-create",
    ),
    path(
        "payroll-statuses/<int:pk>/",
        views.PayrollStatusRetrieveUpdateDestroyView.as_view(),
        name="payroll-statuses-retrieve-update-destroy",
    ),
    path(
        "expense-statuses/",
        views.ExpenseStatusListCreateView.as_view(),
        name="expense-statuses-list-create",
    ),
    path(
        "expense-statuses/<int:pk>/",
        views.ExpenseStatusRetrieveUpdateDestroyView.as_view(),
        name="expense-statuses-retrieve-update-destroy",
    ),
    path(
        "leave-types/",
        views.LeaveTypesListCreateView.as_view(),
        name="leave-types-list-create",
    ),
    path(
        "leave-types/<int:pk>/",
        views.LeaveTypesRetrieveUpdateDestroyView.as_view(),
        name="leave-types-retrieve-update-destroy",
    ),
    path(
        "user-types/",
        views.UserTypesListCreateView.as_view(),
        name="user-types-list-create",
    ),
    path(
        "user-types/<int:pk>/",
        views.UserTypesRetrieveUpdateDestroyView.as_view(),
        name="user-types-retrieve-update-destroy",
    ),
    path(
        "quickbooks/access_token/",
        views.get_access_token,
        name="get_access_token",
    ),
    path(
        "quickbooks/refresh_token/",
        views.get_refresh_token,
        name="refresh_token",
    ),
]
