# Generated by Django 5.0.3 on 2024-04-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsets_management', '0001_initial'),
        ('users', '0009_alter_useraccount_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='optionsets_management.usertypes'),
        ),
    ]
