# Generated by Django 5.0.3 on 2024-05-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0048_alter_administrativedetails_passport_number_and_more'),
        ('employer_management', '0011_alter_employer_job_title_and_more'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gross_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Management_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(null=True)),
                ('forex_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invoice_file', models.FileField(null=True, upload_to='invoice_files/')),
                ('invoice_id', models.IntegerField(null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_status', models.IntegerField(default=0, null=True)),
                ('signing_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_management_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('work_permit_costs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(to='employee_management.employee')),
                ('employer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_invoice', to='employer_management.employer')),
                ('employer_costs', models.ManyToManyField(to='invoice_management.cost')),
                ('expenses', models.ManyToManyField(to='invoice_management.expense')),
                ('gross_salaries', models.ManyToManyField(to='invoice_management.gross_salary')),
                ('invoice_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optionsets_management.invoicetype')),
                ('management_fees', models.ManyToManyField(to='invoice_management.management_fee')),
            ],
        ),
    ]
