# Generated by Django 5.0.3 on 2024-05-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0013_employer_accepted_currency'),
        ('invoice_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_invoice', to='employer_management.employer'),
        ),
    ]
