# Generated by Django 5.0.3 on 2024-04-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.CharField(default='', max_length=255, null=True)),
                ('symbol', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'A. AcceptedCurrencies',
                'verbose_name_plural': 'A. AcceptedCurrencies',
            },
        ),
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'B. ContractTerm',
                'verbose_name_plural': 'B. ContractTerms',
            },
        ),
        migrations.CreateModel(
            name='EmploymentEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'C. EmploymentEligibility',
                'verbose_name_plural': 'C. EmploymentEligibilities',
            },
        ),
        migrations.CreateModel(
            name='EorPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'D. EorPrices',
                'verbose_name_plural': 'D. EorPrices',
            },
        ),
        migrations.CreateModel(
            name='ExpenseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'K. ExpenseStatus',
                'verbose_name_plural': 'K. ExpenseStatuses',
            },
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'E. HealthInsurance',
                'verbose_name_plural': 'E. HealthInsurances',
            },
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'F. InvoiceType',
                'verbose_name_plural': 'F. InvoiceTypes',
            },
        ),
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'L. LeaveTypes',
                'verbose_name_plural': 'L. LeaveTypes',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'G. MaritalStatus',
                'verbose_name_plural': 'G. MaritalStatuses',
            },
        ),
        migrations.CreateModel(
            name='PayrollPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'H. PayrollPrices',
                'verbose_name_plural': 'H. PayrollPrices',
            },
        ),
        migrations.CreateModel(
            name='PayrollStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'J. PayrollStatus',
                'verbose_name_plural': 'J. PayrollStatuses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'I. Product',
                'verbose_name_plural': 'I. Products',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'M. UserTypes',
                'verbose_name_plural': 'M. UserTypes',
            },
        ),
    ]
