# Generated by Django 5.0.3 on 2024-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QB_Access_Token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('QB_Refresh_Token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'N. QuickBook',
                'verbose_name_plural': 'N. QuickBooks',
            },
        ),
    ]
