# Generated by Django 5.0.3 on 2024-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsets_management', '0002_quickbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quickbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
