# Generated by Django 5.0.3 on 2024-05-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsets_management', '0003_alter_quickbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbook',
            name='QB_Access_Token',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
