# Generated by Django 5.0.3 on 2024-05-03 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0048_alter_administrativedetails_passport_number_and_more'),
        ('employer_management', '0011_alter_employer_job_title_and_more'),
        ('partner_management', '0012_partnermissinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payslip_files/')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(null=True, upload_to='payslips/')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('processed', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_employees', to='employee_management.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_employers', to='employer_management.employer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_partners', to='partner_management.partner')),
                ('payslip_files', models.ManyToManyField(to='payslip_management.payslipfile')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
            },
        ),
    ]
