# Generated by Django 5.0.1 on 2024-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField()),
                ('contract_type', models.CharField(choices=[('freelance', 'Freelance'), ('employer_of_record', 'Employer of Record'), ('payroll', 'Payroll')], max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
