# Generated by Django 5.0.3 on 2024-05-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0048_alter_administrativedetails_passport_number_and_more'),
        ('invoice_management', '0001_initial'),
        ('partner_management', '0012_partnermissinginfo'),
        ('payroll_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False, null=True)),
                ('payroll_month', models.DateField()),
                ('contracts', models.ManyToManyField(to='payroll_management.contract')),
                ('employees', models.ManyToManyField(to='employee_management.employee')),
                ('invoices', models.ManyToManyField(to='invoice_management.invoice')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_payroll', to='partner_management.partner')),
            ],
            options={
                'verbose_name_plural': 'Partner Payroll',
            },
        ),
    ]
