# Generated by Django 5.0.3 on 2024-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0002_partnerpayroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpayroll',
            name='payroll_month',
            field=models.DateField(null=True),
        ),
    ]
