# Generated by Django 5.0.3 on 2024-05-03 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0003_alter_partnerpayroll_payroll_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpayroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerpayroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
