# Generated by Django 5.0.3 on 2024-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0007_alter_contract_eor_contract_file'),
        ('payroll_management', '0004_partnerpayroll_created_at_partnerpayroll_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AlterField(
            model_name='partnerpayroll',
            name='contracts',
            field=models.ManyToManyField(to='contract_management.contract'),
        ),
    ]
