# Generated by Django 5.0.3 on 2024-04-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_management', '0033_alter_address_country'),
        ('employee_management', '0046_remove_employeecompensation_currency_and_more'),
        ('employer_management', '0010_remove_employercompanyinfo_country_of_incorporation'),
        ('optionsets_management', '0001_initial'),
        ('partner_management', '0009_partner_created_at_partner_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('role_description', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_cost', models.FloatField(default=0.0, null=True)),
                ('management_fee', models.FloatField(default=0.0, null=True)),
                ('work_permit_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('work_permit_renewal', models.BooleanField(default=True, null=True)),
                ('onboarding_status', models.IntegerField(default=0, null=True)),
                ('probation_period', models.CharField(choices=[('standard', 'Standard probation period'), ('specific', 'Specific probation period')], max_length=100, null=True)),
                ('probation_period_description', models.CharField(blank=True, max_length=255, null=True)),
                ('working_schedule', models.CharField(choices=[('standard', 'Standard working schedule'), ('specific', 'Specific working schedule')], max_length=100, null=True)),
                ('working_schedule_description', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_time_off', models.CharField(choices=[('standard', 'Standard paid time off'), ('specific', 'Specific paid time off')], max_length=100, null=True)),
                ('paid_time_off_description', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_work_address', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_contract_term', to='optionsets_management.contractterm')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_country', to='country_management.country')),
                ('eligibility', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_eligibility', to='optionsets_management.employmenteligibility')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee', to='employee_management.employee')),
                ('employee_home_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_home_address', to='country_management.address')),
                ('employer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_employer', to='employer_management.employer')),
                ('partner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_partner', to='partner_management.partner')),
                ('payroll_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_payroll_status', to='optionsets_management.payrollstatus')),
            ],
            options={
                'verbose_name': 'A. Contract Information',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('signing_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('other_bonus', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance', to='optionsets_management.healthinsurance')),
                ('contract', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='contract_management.contract')),
            ],
            options={
                'verbose_name': 'B. Compensation Information',
            },
        ),
        migrations.CreateModel(
            name='MissingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_employer_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_employer_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employ_contract_image', models.ImageField(null=True, upload_to='contract_images/')),
                ('eor_contract_file', models.FileField(null=True, upload_to='eor_contract_images/')),
                ('work_permit_copy', models.FileField(null=True, upload_to='work_permit_copy/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_detail', to='contract_management.contract')),
            ],
            options={
                'verbose_name': 'C. Missing Details',
            },
        ),
    ]
