# Generated by Django 5.0.3 on 2024-04-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='other_bonus',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='signing_bonus',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingdetail',
            name='custom_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingdetail',
            name='first_employer_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingdetail',
            name='first_gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingdetail',
            name='general_employer_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingdetail',
            name='months_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
