# Generated by Django 5.0.3 on 2024-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0002_alter_compensation_gross_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='other_bonus',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_time_off_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='role_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_permit_nature',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
