# Generated by Django 5.0.3 on 2024-05-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0003_alter_compensation_other_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='eor_contract_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
