# Generated by Django 5.0.3 on 2024-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0004_contract_eor_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='custom_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='employ_contract_image',
            field=models.ImageField(null=True, upload_to='contract_images/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='eor_contract_file',
            field=models.FileField(null=True, upload_to='eor_contract_images/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_employer_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='general_employer_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='months_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_permit_copy',
            field=models.FileField(null=True, upload_to='work_permit_copy/'),
        ),
        migrations.DeleteModel(
            name='MissingDetail',
        ),
    ]
