# Generated by Django 5.0.3 on 2024-05-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0005_contract_custom_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='work_permit_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
