# Generated by Django 5.0.3 on 2024-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0006_contract_work_permit_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='eor_contract_file',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
