# Generated by Django 5.0.3 on 2024-03-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
        ('employer_management', '0003_rename_city1_employercompanyaddress_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_id', to='employer_management.employer'),
        ),
    ]
