# Generated by Django 5.0.3 on 2024-03-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_employeecontract_ending_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='employee_contract',
            new_name='employee',
        ),
    ]
