# Generated by Django 5.0.3 on 2024-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_rename_employee_compensation_employeecompensation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
