# Generated by Django 5.0.3 on 2024-03-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_employee_onboarding_status'),
        ('employer_management', '0004_employer_onboarding_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='employer_management.employer'),
        ),
    ]
