# Generated by Django 5.0.3 on 2024-03-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_remove_employee_employer_id_employee_employer'),
        ('partner_management', '0003_alter_partner_options_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='partner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partner_management.partner'),
        ),
    ]
