# Generated by Django 5.0.3 on 2024-03-30 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0027_alter_countryoverview_country_description_and_more'),
        ('employee_management', '0008_employee_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='country_management.country'),
        ),
    ]
