# Generated by Django 5.0.3 on 2024-03-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_alter_employee_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='ending_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='employeecontract',
            old_name='starting_date',
            new_name='start_date',
        ),
    ]
