# Generated by Django 5.0.3 on 2024-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_rename_ending_date_employeecontract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='management_fee',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
