# Generated by Django 5.0.3 on 2024-04-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0027_alter_countryoverview_country_description_and_more'),
        ('employee_management', '0011_employee_management_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_currency', to='country_management.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_renewal',
            field=models.BooleanField(default=True),
        ),
    ]
