# Generated by Django 5.0.3 on 2024-04-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_remove_employee_first_name_remove_employee_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
