# Generated by Django 5.0.3 on 2024-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_remove_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Onboarding', 'Onboarding'), ('Onpayroll', 'Onpayroll'), ('Dismissed', 'Dismissed')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'F. Payroll Status',
                'verbose_name_plural': 'F. Payroll Status',
            },
        ),
    ]
