# Generated by Django 5.0.3 on 2024-04-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0016_payrollstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_status', to='employee_management.payrollstatus'),
        ),
    ]
