# Generated by Django 5.0.3 on 2024-04-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0018_administrativedetails_clientdetails_emergencycontact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativedetails',
            options={'verbose_name': 'I. Administrative Detail'},
        ),
        migrations.AlterModelOptions(
            name='clientdetails',
            options={'verbose_name': 'J. Client Detail'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name': 'H. Emergency Contact'},
        ),
        migrations.AlterModelOptions(
            name='homeaddress',
            options={'verbose_name': 'G. Home Address'},
        ),
        migrations.AlterField(
            model_name='administrativedetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_detail', to='employee_management.employee'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_detail', to='employee_management.employee'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='employee_management.employee'),
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='', max_length=255, null=True)),
                ('account_type', models.CharField(default='', max_length=255, null=True)),
                ('account_details', models.CharField(default='', max_length=255, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'K. Payment Information',
            },
        ),
    ]
