# Generated by Django 5.0.3 on 2024-04-02 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0019_alter_administrativedetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_employer_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_employer_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passport_image', models.ImageField(null=True, upload_to='passport_images/')),
                ('employ_contract_image', models.ImageField(null=True, upload_to='employ_contract_images/')),
                ('eor_contract_file', models.FileField(null=True, upload_to='eor_contract_images/')),
                ('work_permit_copy', models.FileField(null=True, upload_to='work_permit_copy/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='missing_detail', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'L. Missing Details',
            },
        ),
    ]
