# Generated by Django 5.0.3 on 2024-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0021_administrativedetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employer_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
