# Generated by Django 5.0.3 on 2024-04-03 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0022_employee_employer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='employee_management.contractterm'),
        ),
    ]
