# Generated by Django 5.0.3 on 2024-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0023_alter_employeecontract_contract_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='other_bonus',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='signing_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
