# Generated by Django 5.0.3 on 2024-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0024_alter_employeecompensation_other_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Seperated', 'Seperated'), ('Registered partnership', 'Registered partnership')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
