# Generated by Django 5.0.3 on 2024-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0025_employee_marital_status_employee_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
