# Generated by Django 5.0.3 on 2024-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0026_emergencycontact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='paid_time_off',
            field=models.CharField(choices=[('standard', 'Standard paid time off'), ('specific', 'Specific paid time off')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='probation_period',
            field=models.CharField(choices=[('standard', 'Standard probation period'), ('specific', 'Specific probation period')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='working_schedule',
            field=models.CharField(choices=[('standard', 'Standard working schedule'), ('specific', 'Specific working schedule')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='account_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], max_length=255, null=True),
        ),
    ]
