# Generated by Django 5.0.3 on 2024-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0027_alter_employeecontract_paid_time_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='administrativedetails',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Seperated', 'Seperated'), ('Registered partnership', 'Registered partnership')], max_length=100, null=True),
        ),
    ]
