# Generated by Django 5.0.3 on 2024-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0028_remove_employee_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='extra_documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='missingdetail',
            name='passport_image',
        ),
        migrations.AddField(
            model_name='administrativedetails',
            name='extra_documents',
            field=models.FileField(null=True, upload_to='extra_documents/'),
        ),
        migrations.AddField(
            model_name='administrativedetails',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='passport_images/'),
        ),
    ]
