# Generated by Django 5.0.3 on 2024-04-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0029_extradocuments_remove_missingdetail_passport_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativedetails',
            name='extra_documents',
        ),
    ]
