# Generated by Django 5.0.3 on 2024-04-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0030_remove_administrativedetails_extra_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extradocuments',
            name='files',
        ),
        migrations.AddField(
            model_name='extradocuments',
            name='administrative_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_details', to='employee_management.administrativedetails'),
        ),
        migrations.AddField(
            model_name='extradocuments',
            name='file',
            field=models.FileField(null=True, upload_to='extra_documents/'),
        ),
        migrations.AlterField(
            model_name='administrativedetails',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_detail', to='employee_management.employee'),
        ),
    ]
