# Generated by Django 5.0.3 on 2024-04-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0031_remove_extradocuments_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extradocuments',
            options={'verbose_name': 'L. Extra Documents'},
        ),
    ]
