# Generated by Django 5.0.3 on 2024-04-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0029_alter_address_options_and_more'),
        ('employee_management', '0033_address_employee_home_address_delete_homeaddress'),
        ('employer_management', '0009_alter_employerverification_options_and_more'),
        ('partner_management', '0005_remove_service_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_address', to='country_management.address'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_description',
        ),
        migrations.RemoveField(
            model_name='employeecompensation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='contract',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='employee_management.employeecontract'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee_management.employee'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='employer_management.employer'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='partner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partner_management.partner'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='role_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_curreycn', to='country_management.currency'),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='health_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_health_insurance', to='employee_management.healthinsurance'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
