# Generated by Django 5.0.3 on 2024-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0034_alter_employee_home_address_remove_employee_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontract',
            name='contract',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee_management.employee'),
        ),
    ]
