# Generated by Django 5.0.3 on 2024-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0035_remove_employeecontract_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractterm',
            name='contract_term',
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_term',
            field=models.CharField(choices=[('definite', 'Definite contract'), ('infinite', 'Indefinite contract')], max_length=100, null=True),
        ),
    ]
