# Generated by Django 5.0.3 on 2024-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0036_remove_contractterm_contract_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Onboarding', 'Onboarding'), ('Onpayroll', 'Onpayroll'), ('Dismissed', 'Dismissed')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PayrollStatus',
        ),
    ]
