# Generated by Django 5.0.3 on 2024-04-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0038_alter_administrativedetails_employee_and_more'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractTerm',
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='health_insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_health_insurance', to='optionsets_management.healthinsurance'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='paid_time_off_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='probation_period_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='working_schedule_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedetails',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marital_status', to='optionsets_management.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_term', to='optionsets_management.contractterm'),
        ),
        migrations.DeleteModel(
            name='HealthInsurance',
        ),
    ]
