# Generated by Django 5.0.3 on 2024-04-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0039_delete_contractterm_and_more'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eligibility',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='optionsets_management.employmenteligibility'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_status', to='optionsets_management.payrollstatus'),
        ),
    ]
