# Generated by Django 5.0.3 on 2024-04-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0040_alter_employee_eligibility_alter_employee_status'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer_cost',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='management_fee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='onboarding_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_permit_nature',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_permit_renewal',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='employer_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='management_fee',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='onboarding_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_status', to='optionsets_management.payrollstatus'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='work_permit_nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='work_permit_renewal',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
