# Generated by Django 5.0.3 on 2024-04-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0041_remove_employee_employer_cost_and_more'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='optionsets_management.payrollstatus'),
        ),
    ]
