# Generated by Django 5.0.3 on 2024-04-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0042_alter_employeecontract_status'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='missingdetail',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='payroll_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_status', to='optionsets_management.payrollstatus'),
        ),
        migrations.AddField(
            model_name='missingdetail',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_detail', to='employee_management.employeecontract'),
        ),
    ]
