# Generated by Django 5.0.3 on 2024-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0043_remove_employeecontract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
