# Generated by Django 5.0.3 on 2024-04-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0031_rename_region_address_state'),
        ('employee_management', '0044_alter_employeecontract_end_date_and_more'),
        ('optionsets_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='home_address',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='country_management.country'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_currency', to='country_management.currency'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='eligibility',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='optionsets_management.employmenteligibility'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='employee_home_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_home_address', to='country_management.address'),
        ),
    ]
