# Generated by Django 5.0.3 on 2024-04-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0045_remove_employee_country_remove_employee_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompensation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='currency',
        ),
    ]
