# Generated by Django 5.0.3 on 2024-04-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0046_remove_employeecompensation_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontract',
            name='contract_term',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='employee_home_address',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='payroll_status',
        ),
        migrations.RemoveField(
            model_name='missingdetail',
            name='contract',
        ),
        migrations.AlterModelOptions(
            name='administrativedetails',
            options={'verbose_name': 'C. Administrative Detail'},
        ),
        migrations.AlterModelOptions(
            name='clientdetails',
            options={'verbose_name': 'E. Client Detail'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name': 'B. Emergency Contact'},
        ),
        migrations.AlterModelOptions(
            name='extradocuments',
            options={'verbose_name': 'D. Extra Documents'},
        ),
        migrations.AlterModelOptions(
            name='paymentinformation',
            options={'verbose_name': 'F. Payment Information'},
        ),
        migrations.DeleteModel(
            name='EmployeeCompensation',
        ),
        migrations.DeleteModel(
            name='EmployeeContract',
        ),
        migrations.DeleteModel(
            name='MissingDetail',
        ),
    ]
