# Generated by Django 5.0.3 on 2024-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0047_remove_employeecontract_contract_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedetails',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedetails',
            name='social_security_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='account_details',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
