# Generated by Django 5.0.1 on 2024-01-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
    ]
