# Generated by Django 5.0.3 on 2024-03-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "country_management",
            "0027_alter_countryoverview_country_description_and_more",
        ),
        ("partner_management", "0003_alter_partner_options_partner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="address_line_1",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="address_line_2",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="city",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="company_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity",
                to="country_management.country",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity",
                to="country_management.currency",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="currency2",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_account_number",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_bank_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_bank_country",
                to="country_management.country",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_bank_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_benificiary_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_iban",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_purpose_code",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_sort_code",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="payments_swift_code",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="qb_sync_token",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="qb_vendor_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="region",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="registration_number",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="vat_tax_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="wise_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="employer_of_record_fee",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="employer_of_record_vat",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="employment_contract_template_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="partner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="partner_management.partner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="payroll_fee",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="payroll_vat",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="work_permit_fee",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="work_permit_vat",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
