# Generated by Django 5.0.3 on 2024-04-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0005_remove_service_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='visa_support',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
