# Generated by Django 5.0.3 on 2024-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0006_entity_visa_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='visa_support',
            field=models.BooleanField(default=False),
        ),
    ]
