# Generated by Django 5.0.3 on 2024-04-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0032_address_country'),
        ('partner_management', '0007_alter_entity_visa_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'A. Partner', 'verbose_name_plural': 'A. Partners'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='job_title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PartnerCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255, null=True)),
                ('registration_number', models.CharField(default='', max_length=255, null=True)),
                ('vat_tax_id', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_company_address', to='country_management.address')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_company_info', to='partner_management.partner')),
            ],
            options={
                'verbose_name': 'B. Partner Company Information',
                'verbose_name_plural': 'B. Partner Company Informations',
            },
        ),
    ]
