# Generated by Django 5.0.3 on 2024-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0010_alter_entity_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='onboarding_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
