# Generated by Django 5.0.3 on 2024-05-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0011_partner_onboarding_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMissingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_per_country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payroll_software', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_missing_info', to='partner_management.partner')),
            ],
            options={
                'verbose_name': 'B. Partner Company Information',
                'verbose_name_plural': 'B. Partner Company Informations',
            },
        ),
    ]
