# Generated by Django 5.0.3 on 2024-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0012_partnermissinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='missing_per_country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='payroll_software',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PartnerMissingInfo',
        ),
    ]
