# Generated by Django 5.0.3 on 2024-05-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0034_alter_address_address_line_1_and_more'),
        ('partner_management', '0014_partner_nda_file_partner_nda_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='country_management.country'),
        ),
    ]
