# Generated by Django 5.0.3 on 2024-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0015_service_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='employer_of_record_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='employer_of_record_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='payroll_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='payroll_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_permit_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_permit_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
