# Generated by Django 5.0.3 on 2024-05-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0034_alter_address_address_line_1_and_more'),
        ('partner_management', '0016_alter_service_employer_of_record_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currency2',
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_address', to='country_management.address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='payment_beneficiary_currency',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servic_country', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entity', to='partner_management.entity'),
        ),
    ]
