# Generated by Django 5.0.3 on 2024-05-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0034_alter_address_address_line_1_and_more'),
        ('partner_management', '0017_remove_entity_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='payment_beneficiary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_beneficiary_currency', to='country_management.currency'),
        ),
    ]
