# Generated by Django 5.0.3 on 2024-05-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0018_alter_entity_payment_beneficiary_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='payment_beneficiary_currency',
            new_name='payments_beneficiary_currency',
        ),
    ]
