# Generated by Django 5.0.3 on 2024-05-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_management', '0019_rename_payment_beneficiary_currency_entity_payments_beneficiary_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='payments_iban',
            new_name='payments_iban_number',
        ),
    ]
