# Generated by Django 5.0.3 on 2024-03-28 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_management', '0027_alter_countryoverview_country_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A. Employer Personal Information',
                'verbose_name_plural': 'A. Employer Personal Informations',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1_1', models.CharField(default='', max_length=255, null=True)),
                ('address_line_2', models.CharField(default='', max_length=255, null=True)),
                ('zip_code', models.CharField(default='', max_length=255, null=True)),
                ('city1', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_of_incorporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='country_management.country')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_company_address', to='employer_management.employer')),
            ],
            options={
                'verbose_name': 'C. Employer Company Address',
                'verbose_name_plural': 'C. Employer Company Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255, null=True)),
                ('registration_number', models.CharField(default='', max_length=255, null=True)),
                ('vat_tax_id', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='country_management.currency')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_company_info', to='employer_management.employer')),
            ],
            options={
                'verbose_name': 'B. Employer Company Information',
                'verbose_name_plural': 'B. Employer Company Informations',
            },
        ),
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_verification', to='employer_management.employer')),
            ],
            options={
                'verbose_name': 'D. Employer Verification',
                'verbose_name_plural': 'D. Employer Verification',
            },
        ),
    ]
