# Generated by Django 5.0.3 on 2024-03-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employercompanyaddress',
            old_name='address_line_1_1',
            new_name='address_line_1',
        ),
    ]
