# Generated by Django 5.0.3 on 2024-03-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0002_rename_address_line_1_1_employercompanyaddress_address_line_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employercompanyaddress',
            old_name='city1',
            new_name='city',
        ),
    ]
