# Generated by Django 5.0.3 on 2024-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0003_rename_city1_employercompanyaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='onboarding_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
