# Generated by Django 5.0.3 on 2024-04-02 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0004_employer_onboarding_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='users',
            field=models.ManyToManyField(related_name='employer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
