# Generated by Django 5.0.3 on 2024-04-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0005_employer_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'A. Employers', 'verbose_name_plural': 'A. Employers'},
        ),
    ]
