# Generated by Django 5.0.3 on 2024-04-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0006_alter_employer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employercompanyaddress',
            old_name='state',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='users',
        ),
    ]
