# Generated by Django 5.0.3 on 2024-04-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0028_address'),
        ('employer_management', '0008_remove_employer_date_of_birth_remove_employer_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerverification',
            options={'verbose_name': 'C. Employer Verification', 'verbose_name_plural': 'C. Employer Verification'},
        ),
        migrations.AddField(
            model_name='employercompanyinfo',
            name='company_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='country_management.address'),
        ),
        migrations.AddField(
            model_name='employercompanyinfo',
            name='country_of_incorporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='country_management.country'),
        ),
        migrations.DeleteModel(
            name='EmployerCompanyAddress',
        ),
    ]
