# Generated by Django 5.0.3 on 2024-04-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0009_alter_employerverification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercompanyinfo',
            name='country_of_incorporation',
        ),
    ]
