# Generated by Django 5.0.3 on 2024-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0010_remove_employercompanyinfo_country_of_incorporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employercompanyinfo',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employercompanyinfo',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employercompanyinfo',
            name='vat_tax_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
