# Generated by Django 5.0.3 on 2024-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0011_alter_employer_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='QB_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
