# Generated by Django 5.0.3 on 2024-05-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0012_employer_qb_customer_id'),
        ('optionsets_management', '0004_alter_quickbook_qb_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='accepted_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optionsets_management.acceptedcurrencies'),
        ),
    ]
