# Generated by Django 5.0.1 on 2024-02-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_category_blog_image_blog_meta_description_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
