# Generated by Django 5.0.1 on 2024-03-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_author_blog_category_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
