# Generated by Django 5.0.1 on 2024-03-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
