# Generated by Django 5.0.1 on 2024-03-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_remove_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content2',
            new_name='content',
        ),
    ]
