# Generated by Django 5.0.1 on 2024-02-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=512)),
                ('currency_name', models.CharField(max_length=512)),
                ('currency_symbol', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('capital', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=512)),
                ('flag', models.URLField()),
                ('holiday_code', models.CharField(max_length=128)),
                ('land_code', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='country_management.currency')),
            ],
        ),
    ]
