# Generated by Django 5.0.1 on 2024-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/'),
        ),
    ]
