# Generated by Django 5.0.1 on 2024-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0002_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
