# Generated by Django 5.0.1 on 2024-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0004_alter_country_options_leave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AddField(
            model_name='country',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
