# Generated by Django 5.0.1 on 2024-02-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0005_alter_leave_options_country_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/'),
        ),
    ]
