# Generated by Django 5.0.1 on 2024-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0006_alter_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
