# Generated by Django 5.0.1 on 2024-02-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0007_country_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='gdp_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gdp_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
