# Generated by Django 5.0.1 on 2024-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0008_country_gdp_growth_country_gdp_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='workforce_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
