# Generated by Django 5.0.1 on 2024-02-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0009_country_workforce_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='county',
            new_name='country',
        ),
    ]
