# Generated by Django 5.0.1 on 2024-03-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0012_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='markdown_description',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
