# Generated by Django 5.0.1 on 2024-03-14 12:21

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0016_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payday',
            new_name='payroll_cycle',
        ),
        migrations.CreateModel(
            name='TaxObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_tax_responsibilites', markdownx.models.MarkdownxField()),
                ('employee_tax_deductions', markdownx.models.MarkdownxField()),
                ('vat', markdownx.models.MarkdownxField()),
                ('tax_incentives', markdownx.models.MarkdownxField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_obligations', to='country_management.country')),
            ],
            options={
                'verbose_name': 'Tax Obligations',
                'verbose_name_plural': 'Tax Obligations',
            },
        ),
    ]
