# Generated by Django 5.0.1 on 2024-03-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0018_alter_country_land_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxobligations',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_obligations', to='country_management.country'),
        ),
    ]
