# Generated by Django 5.0.1 on 2024-03-18 09:18

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0019_alter_taxobligations_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.CreateModel(
            name='EmployeeBenefitsAndEntitlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_benefits', markdownx.models.MarkdownxField(help_text="Create a detailed guide of the Mandatory Employee Benefits in [Country]. Don't add the resources in a separate heading, but include them in the content where needed. Don't include any disclaimer or reminders. Only give the guide, no introductions or conclusions. When creating titles, start from H2 headings.")),
                ('optional_benefits', markdownx.models.MarkdownxField(help_text="Create a detailed guide of the Optional Employee Benefits in [Country]. Don't add the resources in a separate heading, but include them in the content where needed. Don't include any disclaimer or reminders. Only give the guide, no introductions or conclusions. When creating titles, start from H2 headings.")),
                ('health_insurance_requirements', markdownx.models.MarkdownxField(help_text="Create a detailed guide of the Health Insurance Requirements for Employees in [Country]. Don't add the resources in a separate heading, but include them in the content where needed. Don't include any disclaimer or reminders. Only give the guide, no introductions or conclusions. When creating titles, start from H2 headings.")),
                ('retirement_plans', markdownx.models.MarkdownxField(help_text="Create a detailed guide of the Retirement Plans for Employees in [Country]. Don't add the resources in a separate heading, but include them in the content where needed. Don't include any disclaimer or reminders. Only give the guide, no introductions or conclusions. When creating titles, start from H2 headings.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_benefits', to='country_management.country')),
            ],
            options={
                'verbose_name': 'Employee Benefits and Entitlements',
                'verbose_name_plural': 'Employee Benefits and Entitlements',
                'ordering': ['country'],
            },
        ),
    ]
