# Generated by Django 5.0.1 on 2024-03-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0021_remove_leave_country_remove_payment_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '1. Country', 'verbose_name_plural': '1. Countries'},
        ),
        migrations.AlterModelOptions(
            name='countryoverview',
            options={'verbose_name': '2. Country Overview', 'verbose_name_plural': '2. Country Overviews'},
        ),
        migrations.AlterModelOptions(
            name='culturalconsiderations',
            options={'ordering': ['country'], 'verbose_name': '15. Cultural Considerations', 'verbose_name_plural': '15. Cultural Considerations'},
        ),
        migrations.AlterModelOptions(
            name='disputeresolutionandlegalcompliance',
            options={'ordering': ['country'], 'verbose_name': '14. Dispute Resolution and Legal', 'verbose_name_plural': '14. Dispute Resolution and Legal'},
        ),
        migrations.AlterModelOptions(
            name='employeebenefitsandentitlements',
            options={'ordering': ['country'], 'verbose_name': '4. Benefits and Entitlements', 'verbose_name_plural': '4. Benefits and Entitlements'},
        ),
        migrations.AlterModelOptions(
            name='employmentagreements',
            options={'ordering': ['country'], 'verbose_name': '6. Employment Agreements', 'verbose_name_plural': '6. Employment Agreements'},
        ),
        migrations.AlterModelOptions(
            name='freelancingandindependentcontracting',
            options={'ordering': ['country'], 'verbose_name': '12. Independent Contracting', 'verbose_name_plural': '12. Independent Contracting'},
        ),
        migrations.AlterModelOptions(
            name='healthandsafetyrequirements',
            options={'ordering': ['country'], 'verbose_name': '13. Health and Safety', 'verbose_name_plural': '13. Health and Safety'},
        ),
        migrations.AlterModelOptions(
            name='remoteworkandflexibleworkarrangements',
            options={'ordering': ['country'], 'verbose_name': '7. Remote and Flexible Work', 'verbose_name_plural': '7. Remote and Flexible Work'},
        ),
        migrations.AlterModelOptions(
            name='salaryandcompensation',
            options={'ordering': ['country'], 'verbose_name': '9. Salary and Compensation', 'verbose_name_plural': '9. Salary and Compensation'},
        ),
        migrations.AlterModelOptions(
            name='standardworkinghoursandovertime',
            options={'ordering': ['country'], 'verbose_name': '8. Working Hours and Overtime', 'verbose_name_plural': '8. Working Hours and Overtime'},
        ),
        migrations.AlterModelOptions(
            name='taxobligations',
            options={'verbose_name': '3. Tax Obligations', 'verbose_name_plural': '3. Tax Obligations'},
        ),
        migrations.AlterModelOptions(
            name='termination',
            options={'ordering': ['country'], 'verbose_name': '11. Termination and Severance', 'verbose_name_plural': '11. Termination and Severance'},
        ),
        migrations.AlterModelOptions(
            name='vacationandleavepolicies',
            options={'ordering': ['country'], 'verbose_name': '10 .Vacation and Leave', 'verbose_name_plural': '10. Vacation and Leave'},
        ),
        migrations.AlterModelOptions(
            name='workersrightsandprotections',
            options={'ordering': ['country'], 'verbose_name': '5. Rights and Protections', 'verbose_name_plural': '5. Rights and Protections'},
        ),
    ]
