# Generated by Django 5.0.1 on 2024-03-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0023_alter_country_options_alter_countryoverview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalconsiderations',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cultural_considerations', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='disputeresolutionandlegalcompliance',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_resolution_and_legal_compliance', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='employeebenefitsandentitlements',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_benefits', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='employmentagreements',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employment_agreements', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='freelancingandindependentcontracting',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='freelancing_and_independent_contracting', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='healthandsafetyrequirements',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='health_and_safety_requirements', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='remoteworkandflexibleworkarrangements',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='remote_work', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='salaryandcompensation',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary_and_compensation', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='standardworkinghoursandovertime',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='standard_working_hours', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='termination',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termination', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='vacationandleavepolicies',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_and_leave', to='country_management.country'),
        ),
        migrations.AlterField(
            model_name='workersrightsandprotections',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workers_rights', to='country_management.country'),
        ),
    ]
