# Generated by Django 5.0.1 on 2024-03-19 14:29

import country_management.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0026_alter_countryoverview_country_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryoverview',
            name='country_description',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Provide an in-depth overview of [Country], covering geographical, historical, and socio-economic aspects. Integrate authoritative sources directly into the narrative to support your descriptions. Return in markdown, start with H2 headings and use H3, H4 if needed and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='cultural_norms_impacting_employment',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the cultural norms in [Country] that influence employment practices, including work-life balance, communication styles, and organizational hierarchies. Incorporate insights from reputable sources to enrich the guide. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='key_industries_and_employment_sectors',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the key industries and employment sectors driving the economy in [Country], highlighting emerging sectors and those with significant employment. Include up-to-date references within the text to substantiate your points. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='countryoverview',
            name='workforce_description',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the characteristics of the workforce in [Country], including demographics, skill levels, and sectoral distribution. Embed relevant statistics and findings from credible sources within the content. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='culturalconsiderations',
            name='communication_styles_in_the_workplace',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the prevalent communication styles in the workplace in [Country], including directness, formality, and the role of non-verbal cues. Embed relevant cultural studies and business practices within the text to offer depth. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='culturalconsiderations',
            name='holidays_and_observances_affecting_business_operations',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Describe the major holidays and observances in [Country] that affect business operations, including statutory holidays, regional observances, and their impact on work schedules. Seamlessly embed cultural and legal references within the text. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='culturalconsiderations',
            name='negotiation_practices',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine negotiation practices in [Country], focusing on approaches, typical strategies, and cultural norms that influence business dealings. Integrate authoritative references to enhance credibility. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='culturalconsiderations',
            name='understanding_hierarchical_structures',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the hierarchical structures prevalent in businesses in [Country], including the impact on decision-making, team dynamics, and leadership styles. Incorporate insights from cultural analysis and management theories directly into the content. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='disputeresolutionandlegalcompliance',
            name='compliance_audits_and_inspections',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the procedures and importance of compliance audits and inspections in [Country], covering who conducts them, frequency, and the consequences of non-compliance. Embed authoritative references within the text to ensure accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='disputeresolutionandlegalcompliance',
            name='international_labor_standards_compliance',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore how [Country] complies with international labor standards, including adherence to conventions and treaties, and the impact on domestic labor laws. Seamlessly integrate relevant international and local legal sources within the text. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='disputeresolutionandlegalcompliance',
            name='labor_courts_and_arbitration_panels',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the structure and function of labor courts and arbitration panels in [Country], including their jurisdiction, process, and typical cases handled. Integrate relevant legal sources to provide a comprehensive overview. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='disputeresolutionandlegalcompliance',
            name='reporting_and_whistleblower_protections',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Discuss the mechanisms for reporting violations and the protections in place for whistleblowers in [Country], highlighting legal provisions and practical considerations. Incorporate credible legal and regulatory references directly into the guide for substantiation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employeebenefitsandentitlements',
            name='health_insurance_requirements',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the health insurance requirements for employees in [Country]. Embed credible sources directly within the guide. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employeebenefitsandentitlements',
            name='mandatory_benefits',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Provide a comprehensive overview of mandatory employee benefits in [Country]. Include authoritative sources within the text to lend credibility. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employeebenefitsandentitlements',
            name='optional_benefits',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the optional employee benefits commonly offered by employers in [Country]. Integrate relevant references into the content for factual support. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employeebenefitsandentitlements',
            name='retirement_plans',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the retirement plans available to employees in [Country]. Incorporate authoritative references to support the discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employmentagreements',
            name='confidentiality_and_non_compete_clauses',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Discuss the confidentiality and non-compete clauses in employment agreements in [Country]. Seamlessly integrate relevant legal sources within the text. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employmentagreements',
            name='essential_clauses',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the essential clauses that should be included in employment agreements in [Country]. Embed authoritative references to support the discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employmentagreements',
            name='probationary_period',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the concept of the probationary period in employment agreements in [Country]. Incorporate credible sources directly into the guide for validation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='employmentagreements',
            name='types_of_employment_agreements',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the various types of employment agreements in [Country]. Integrate relevant legal sources within the text to provide accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='freelancingandindependentcontracting',
            name='difference_employees_and_contractors',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the legal distinctions between employees and independent contractors in [Country]. Integrate relevant legal references within the text to ensure accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='freelancingandindependentcontracting',
            name='independent_contracting',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the nuances of independent contracting in [Country], including contract structures, negotiation practices, and common industries. Embed authoritative sources to substantiate the discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='freelancingandindependentcontracting',
            name='intellectual_property_rights',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine intellectual property rights considerations for freelancers and independent contractors in [Country]. Incorporate credible legal sources directly into the text for validation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='freelancingandindependentcontracting',
            name='tax_and_insurance',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Describe the tax obligations and insurance options for freelancers and independent contractors in [Country]. Seamlessly integrate relevant tax legislation and insurance norms within the guide. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='healthandsafetyrequirements',
            name='health_and_safety_laws',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Provide an in-depth overview of health and safety laws in [Country]. Embed relevant legal references within the text for accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='healthandsafetyrequirements',
            name='occupational_health_and_safety',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the standards and practices for occupational health and safety in [Country].. Incorporate authoritative sources directly into the content for substantiation. UReturn in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='healthandsafetyrequirements',
            name='workplace_accidents',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Discuss the protocols for dealing with workplace accidents in [Country], including reporting requirements, investigation processes, and compensation claims. Embed credible legal and regulatory references to support the discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='healthandsafetyrequirements',
            name='workplace_inspection',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the role and procedures for workplace inspections in [Country], highlighting inspection criteria, frequency, and follow-up actions. Seamlessly integrate relevant regulations and guidelines within the guide. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='remoteworkandflexibleworkarrangements',
            name='data_protection_and_privacy',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Discuss data protection and privacy considerations for remote employees in [Country], highlighting employer obligations, employee rights, and best practices for securing personal and company data. Incorporate authoritative references to support the discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='remoteworkandflexibleworkarrangements',
            name='flexible_work_arrangements',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine flexible work arrangements in [Country], including part-time work, flexitime, job sharing, and telecommuting. Detail the equipment and expense reimbursements policies, embedding applicable legal sources for verification. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='remoteworkandflexibleworkarrangements',
            name='remote_work',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Provide an in-depth analysis of remote work policies and practices in [Country], covering legal regulations, technological infrastructure requirements, and employer responsibilities. Integrate relevant laws and guidelines within the text to ensure accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='salaryandcompensation',
            name='bonuses_and_allowances',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the variety of bonuses and allowances offered to employees in [Country]. Incorporate credible sources directly into the guide for validation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='salaryandcompensation',
            name='market_competitive_salaries',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Analyze the concept of market competitive salaries in [Country]. Integrate authoritative financial and employment resources within the content for substantiation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='salaryandcompensation',
            name='minimum_wage',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the minimum wage regulations in [Country]. Embed relevant legislative references to ensure accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='salaryandcompensation',
            name='payroll_cycle',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the payroll cycle practices in [Country]. Seamlessly integrate authoritative financial and legal references within the text. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='standardworkinghoursandovertime',
            name='night_shift_and_weekend_regulations',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Discuss the specific regulations for night shift and weekend work in [Country]. Seamlessly integrate applicable legal references within the text. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='standardworkinghoursandovertime',
            name='overtime',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the rules and compensation for overtime work in [Country]. Embed relevant legislation and guidelines to ensure accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='standardworkinghoursandovertime',
            name='rest_periods_and_breaks',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the entitlements to rest periods and breaks for workers in [Country]. Incorporate authoritative sources directly into the guide for verification. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='standardworkinghoursandovertime',
            name='standard_working_hours',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Outline the regulations governing standard working hours in [Country]. Integrate applicable legal references within the content to provide authoritative support. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='taxobligations',
            name='employee_tax_deductions',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the employee tax deductions in [Country]. Embed relevant references within the text to enhance credibility. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='taxobligations',
            name='employer_tax_responsibilites',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Outline the employer tax responsibilities in [Country]. Ensure authoritative resources are integrated within the guide to provide verification. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='taxobligations',
            name='tax_incentives',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the tax incentives available to businesses in [Country]. Incorporate relevant sources within the guide for factual accuracy. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='taxobligations',
            name='vat',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the Value-Added Tax (VAT) implications for services in [Country]. Integrate authoritative sources directly into the content for substantiation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='termination',
            name='notice_period',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explain the legal requirements for notice periods in [Country] during employment termination. Embed relevant labor law references within the text for credibility. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='termination',
            name='severance_pay',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the severance pay entitlements in [Country]. Incorporate authoritative legal sources to substantiate the information presented. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='termination',
            name='termination_process',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Describe the termination process of employees in [Country]. Seamlessly integrate applicable legal guidelines within the text for validation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='vacationandleavepolicies',
            name='holiday_leave',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the vacation leave entitlements in [Country]. Integrate relevant labor laws and guidelines within the text to lend authority. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='vacationandleavepolicies',
            name='public_holidays',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore the public holidays observed in [Country]. Embed authoritative sources to validate the information. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='vacationandleavepolicies',
            name='types_of_leave',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine the various types of leave available to employees in [Country]. Incorporate credible legal and regulatory references directly into the guide for substantiation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='workersrightsandprotections',
            name='discrimination',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Detail the anti-discrimination laws in [Country], focusing on protected characteristics, redress mechanisms, and employer responsibilities. Embed credible sources directly into the content for validation. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='workersrightsandprotections',
            name='health_and_safety',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explore health and safety regulations in the workplace in [Country], discussing employer obligations, employee rights, and enforcement agencies. Seamlessly integrate authoritative sources to substantiate the information. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='workersrightsandprotections',
            name='termination',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Delve into the regulations surrounding the termination of employment in [Country], covering lawful grounds for dismissal, notice requirements, and severance pay. Ensure that authoritative resources are integrated within the text to support your discussion. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
        migrations.AlterField(
            model_name='workersrightsandprotections',
            name='working_conditions',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Explain the standards for working conditions in [Country], including work hours, rest periods, and ergonomic requirements. Incorporate relevant references within the guide to enhance reliability. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
    ]
