# Generated by Django 5.0.3 on 2024-04-11 23:55

import country_management.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0028_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'P. Address'},
        ),
        migrations.AlterField(
            model_name='remoteworkandflexibleworkarrangements',
            name='flexible_work_arrangements',
            field=country_management.custom_fields.CustomMarkdownxField(help_text="Examine flexible work arrangements in [Country], including part-time work, flexitime, job sharing, and telecommutinP Detail the equipment and expense reimbursements policies, embedding applicable legal sources for verification. Return in markdown, start with H2 headings and use H3, H4 if needed. Only return the guide and do not add disclaimers. Don't add invalid URL's"),
        ),
    ]
