# Generated by Django 5.0.3 on 2024-04-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0029_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
