# Generated by Django 5.0.3 on 2024-04-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0030_address_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='region',
            new_name='state',
        ),
    ]
