# Generated by Django 5.0.3 on 2024-04-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_management', '0031_rename_region_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
